### ISSUE TITLE
pls release

### ISSUE THREAD

**Issue by Svenmax** [n0tic/SteamServerCreationTool#2]
thx for the project

can u release an exe file ?

**Comment by n0tic** [comment]
As per your request, this application has been built and a pre-release has been added to the project.

May i request that you, as a user and a tester, provide some feedback once you have tested this application.
I would be very glad if you could throw in some critique or just regular feedback regarding the usage.

Future plans is to overhaul the design to make it even more user friendly but right now, life has other priorities.

Thanks for showing interest, enjoy.

**Comment by Svenmax** [comment]
> As per your request, this application has been built and a pre-release has been added to the project.


Thank you for your quick follow-up, I will test and give feedback.
